### ISSUE TITLE
ilastik: used channel priority might produce inconsistent environments

### ISSUE THREAD

**Issue by k-dominik** [drpatelh/nf-core-imcyto#1]
https://github.com/drpatelh/nf-core-imcyto/blob/2bb7dffe4d0cea14ced76fd296b098f2629a3240/environment_ilastik.yml#L2-L5

AFAIK channels are prioritized in the order as given in the config. For ilastik, you need to list `ilastik-forge` first. Otherwise "our" packages might be shadowed by the ones from `conda-forge`.

We have also updated all our dependencies recently on `ilastik-forge` and moved all "old" packages (that are not compatible with the current `conda-forge` ones) to the label `cf201901`. So in order to get a valid `1.3.2` environment, I think you'd have to use

```
     channels:
        - ilastik-forge/label/cf201901
        - conda-forge/label/cf201901
        - defaults
```

Furthermore, 

https://github.com/drpatelh/nf-core-imcyto/blob/2bb7dffe4d0cea14ced76fd296b098f2629a3240/environment_ilastik.yml#L6-L7

we currently don't maintain the `no-gui` recipes as we are not using them atm.

Have you ever tried building your docker container just from the ilastik binary (and then running via `run_ilastik.sh`?

**Comment by drpatelh** [comment]
@k-dominik Thank you very much for the quick response, and for opening this issue.

I am hoping to write this pipeline in a way in which it can be used with `conda`, `Docker` or `Singularity`. The idea is to maintain a single conda environment file containing the software dependencies, and this is then subsequently built within a `Docker` container. This just means the end-user can execute the pipeline using various means. If you think its possible, what do you think is the easiest way to maintain the `ilastik` software using this approach? Unfortunately, I have had to create 2 `conda` environment files because `cellprofiler` and `ilastik` wont build in a single environment but I can deal with that.

I dont necessarily need to have version `1.3.2`, it was just the latest at the time. I can update the conda file to version `1.3.3` if you think its best. Also, I selected `ilastik-dependencies-no-solvers-no-gui` because I will be running `ilastik` in `--headless` mode so thought it would be a slimmer install.

I have to admit that my knowledge of image analysis is slim at best! Any tips would be well appreciated. Id rather get it right based on your expert opinion. Thanks again.

**Comment by k-dominik** [comment]
Hi @drpatelh,

the `ilastik-dependencies-no-solvers-no-gui` was really just an explorative recipe to see, whether one can get rid of the gui depenencies in an easy way. I don't think it was a success. I've had a look at the dependencies that are installed and can see that `qt` for example is still in it. It is too integrated into ilastik atm to rip out. So I think you can safely resort to using `ilastik-dependencies-no-solvers`.

As for the idea to maintain a single environment I don't think that this is the easiest of all approaches. We are pretty strict on some of our dependencies and the folks at cellprofiler might be, too. If you want to use the headless mode, why don't you create dedicated docker containers for each tool you want to use? This would give you a bit of flexibility with your pipelining and you can then use something like kubernetes to automate your application.

Cheers

**Comment by drpatelh** [comment]
The pipeline doesnt support Conda to overcome the issues mentioned above. We are now directly using the `Ilastik` Docker builds available on Dockerhub via the official repo. Thanks @k-dominik !
https://github.com/nf-core/imcyto/blob/2e830372779df115b11871f58259d780c1ba02ac/conf/base.config#L47
